# Generated by Django 5.0 on 2023-12-12 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(max_length=100, verbose_name='Course Name')),
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Course Code')),
                ('duration', models.IntegerField(verbose_name='Course Duration')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Course Creation Date')),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='website_cou_name_52ec13_idx')],
            },
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('name', models.CharField(max_length=100, verbose_name='Scheme Name')),
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Scheme Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Scheme Creation Date')),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='website_sch_name_5de2ec_idx')],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('name', models.CharField(max_length=50, verbose_name='State Name')),
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='State Code')),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='website_sta_name_619bfc_idx')],
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('name', models.CharField(max_length=100, verbose_name='College Name')),
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='College Code')),
                ('city', models.CharField(max_length=100, verbose_name='College City')),
                ('pincode', models.CharField(max_length=6, verbose_name='College Pincode')),
                ('address', models.CharField(max_length=200, verbose_name='College Address')),
                ('phone', models.CharField(max_length=10, verbose_name='College Phone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='College Creation Date')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.state')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('uid', models.CharField(max_length=14, primary_key=True, serialize=False, verbose_name='UID')),
                ('admission_year', models.IntegerField(verbose_name='Admission Year')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Student Creation Date')),
                ('aadhar_id', models.CharField(max_length=12, verbose_name='Aadhar ID')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.college')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.course')),
                ('scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.scheme')),
            ],
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['name'], name='website_col_name_c845e3_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['aadhar_id'], name='website_stu_aadhar__c976a3_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['first_name', 'last_name'], name='website_stu_first_n_74bf65_idx'),
        ),
    ]
