# Generated by Django 5.0 on 2023-12-19 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_college_code_alter_college_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='aadhar_id',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(12), django.core.validators.MaxLengthValidator(12)], verbose_name='Aadhar ID'),
        ),
    ]
