# Generated by Django 5.0 on 2023-12-19 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_student_admission_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='serial_no',
            field=models.CharField(default=888, max_length=3, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(3)], verbose_name='Serial No'),
            preserve_default=False,
        ),
    ]
