# Generated by Django 5.0 on 2023-12-20 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_student_serial_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='code',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(3)], verbose_name='College Code'),
        ),
    ]
